### ISSUE TITLE
Seeds on nightmare lv1 crash the game

### ISSUE THREAD

**Issue by Lakifume** [Jarno458/TsRandomizer#109]
Just getting started with this rando and first thing I noticed is that every difficulty loads fine except for nightmare lv1 which instantly kicks you out of the game when picking that option. The error in the log is this:

Exception: Object reference not set to an instance of an object.
   at TsRandomizer.Extensions.Dynamic.<>c.<TryInvokeMember>b__5_0(Object a) in E:\TimeSpinnerModding\TsRanomizer\TsRandomizer\Extensions\ReflectExtensions.cs:line 77
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at TsRandomizer.Extensions.Dynamic.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result) in E:\TimeSpinnerModding\TsRanomizer\TsRandomizer\Extensions\ReflectExtensions.cs:line 76
   at CallSite.Target(Closure , CallSite , Object , Object , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at TsRandomizer.Screens.GameDifficultyMenuScreen.<UpdateHardModeDifficulties>b__10_0(PlayerIndex p) in E:\TimeSpinnerModding\TsRanomizer\TsRandomizer\Screens\GameDifficultyMenuScreen.cs:line 67
   at CallSite.Target(Closure , CallSite , Action`1 , Object )
   at TsRandomizer.Screens.Menu.MenuEntry.<>c__DisplayClass25_0.<Create>b__0(Object o, EventArgs args) in E:\TimeSpinnerModding\TsRanomizer\TsRandomizer\Screens\Menu\MenuEntry.cs:line 73
   at Timespinner.GameStateManagement.MenuEntry.OnSelectEntry(PlayerIndex playerIndex)
   at Timespinner.GameStateManagement.MenuEntryCollection.SelectEntry(PlayerIndex playerIndex)
   at Timespinner.GameStateManagement.Screens.BaseClasses.Menu.MenuScreen.HandleInput(InputState input)
   at Timespinner.GameStateManagement.ScreenManager.ScreenManager.UpdateScreens(GameTime gameTime)
   at Timespinner.GameStateManagement.ScreenManager.ScreenManager.Update(GameTime gameTime)
   at TsRandomizer.Screens.ScreenManager.Update(GameTime gameTime) in E:\TimeSpinnerModding\TsRanomizer\TsRandomizer\Screens\ScreenManager.cs:line 64
   at Microsoft.Xna.Framework.Game.Update(GameTime gameTime)
   at Timespinner.TimespinnerGame.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.RunLoop()
   at Microsoft.Xna.Framework.Game.Run()
   at TsRandomizer.Program.<>c.<StartTimeSpinner>b__7_0() in E:\TimeSpinnerModding\TsRanomizer\TsRandomizer\Program.cs:line 88
   at TsRandomizer.Program.WithExceptionLogging(Action action) in E:\TimeSpinnerModding\TsRanomizer\TsRandomizer\Program.cs:line 99

**Comment by Jarno458** [comment]
Oops, seems like it doesnt want to load nightmare unless you cleared the game atleast once. i need to fix that. thanks for reporting

**Comment by Jarno458** [comment]
Should be fixed on the release of 1.21.0
